// src/views/query/mongodb/query-area/result.jsx
let uid = 0
const trans = {
  Array (data) {
    return data.map((d, i) => trans.entry(d, i))
  },
  Object (data) {
    return Object.keys(data).map((k) => trans.entry(data[k], k))
  },
  entry (value, prop = '') {
    const type = Object.prototype.toString.call(value).slice(8, -1)
    if (trans[type]) {
      return { children: trans[type](value), prop, type, key: uid++ }
    } else {
      value = String(value)
      return { value, prop, type, key: uid++ }
    }
  }
}
export default {
  props: {
    result: {
      default: () => [],
      type: Array
    }
  },
  data () {
    return {
      pagination: {
        current: 1,
        pageSize: 10,
        position: 'top',
        showSizeChanger: true,
        pageSizeOptions: ['10', '20', '30', '40']
      },
      columns: [
        { dataIndex: 'prop', title: '属性' },
        { dataIndex: 'type', title: '类型' },
        { dataIndex: 'value', title: '值' },
      ],
      dataSource: [],
      expandedRowKeys: [],
      scroll: { y: 400 },
    }
  },
  watch: {
    result () {
      uid = 0
      this.setData()
    }
  },
  methods: {
    change (pagination) {
      this.pagination = { ...this.pagination, ...pagination }
      this.setData()
    },
    setData () {
      const { current, pageSize } = this.pagination
      this.dataSource = this.result
        .slice((current - 1) * pageSize, current * pageSize)
        .map(data => trans.entry(data))
      this.$nextTick(() => {
        this.expandedRowKeys = this.dataSource.map(d => d.key)
      })
    },
    expandedRowsChange (keys) {
      this.expandedRowKeys = keys
    }
  },
  render () {
    const props = { ...this.$data, size: 'small', bordered: true }
    return <a-table
      props={props}
      onChange={this.change}
      onExpandedRowsChange={this.expandedRowsChange}
    />
  }
}

// src/views/query/mysql/query-area/result.jsx
import Vue from 'vue'
const Result = Vue.extend({
  props: {
    records: {
      type: Array,
      default () { return [] }
    },
    title: {
      type: Array,
      default () { return [] }
    }
  },
  data () {
    return {
      uid: 0,
      rowKey: '__DMS_QYERY_UID__',
      dataSource: [],
      scroll: { y: 400, x: 1000 }
    }
  },
  computed: {
    columns () {
      return [
        { title: '#', width: 40, customRender: (_text, _record, index) => <span>{ index + 1 }</span> },
        ...this.title.map(title => {
          if (typeof title === 'object') {
            return title
          }
          return {
            title,
            dataIndex: title,
            width: 100
          }
        })
      ]
    }
  },
  watch: {
    records: {
      immediate: true,
      handler () {
        this.dataSource = this.records.map((data) => {
          return {
            [this.rowKey]: this.uid++,
            ...data
          }
        })
      }
    }
  },
  methods: {
    authScrollHeight () {
      const body = this.$el.querySelector('.ant-table-body')
      if (body) {
        const { top } = body.getBoundingClientRect()
        this.scroll.y = window.innerHeight - top - 16
      }
    }
  },
  render () {
    const { dataSource, columns, rowKey } = this
    return <a-table
      class="mini-row-table"
      props={{
        rowKey,
        bordered: true,
        dataSource,
        columns,
        size: 'small',
        pagination: {
          position: 'top',
          showSizeChanger: true,
          pageSizeOptions: ['10', '50', '100', '200']
        },
        scroll: this.scroll
      }}
    />
  }
})

export default Result
